[package]
name = "mkl"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]

[lib]
name = "mkl"
path = "src/lib.rs"

#[[bin]]
#name = "test"
#path = "tools/test.rs"

[dependencies]
libc = "*"
